
import { Profile } from '../types';

export const currentUser: Profile = {
  id: 1,
  name: 'Priya Patel',
  username: 'priya_patel',
  email: 'priya.patel@example.com',
  phone: '9123456789',
  password: 'password123',
  age: 28,
  gender: 'Female',
  religion: 'Hindu',
  motherTongue: 'Gujarati',
  location: 'Mumbai, Maharashtra',
  coordinates: { latitude: 19.0760, longitude: 72.8777 },
  occupation: 'Software Engineer',
  education: 'B.Tech',
  height: "5' 5\"",
  about: "I'm a creative and ambitious software engineer with a passion for technology and travel. In my free time, I enjoy hiking, painting, and exploring new cafes in the city. I'm looking for a partner who is intelligent, has a good sense of humor, and shares my love for adventure.",
  interests: ['Travel', 'Hiking', 'Painting', 'Technology'],
  imageUrls: ['https://picsum.photos/seed/priya/400/600'],
  lifestyle: 'Vegetarian',
  isVerified: false,
  privacySettings: {
    showAge: true,
    showLocation: true,
    showOccupation: true,
    showFollowers: true,
    showReligion: true,
    showMotherTongue: true,
    showEducation: true,
    showHeight: true,
    showLifestyle: true,
    showSocialMedia: true,
  },
  socialMedia: [
    { platform: 'LinkedIn', url: 'https://www.linkedin.com/in/priya-patel' },
    { platform: 'Instagram', url: 'https://www.instagram.com/priya_patel' },
  ],
  visitorCount: 42,
  joinedDate: '2023-06-01',
  lastSeen: new Date().toISOString(),
};
