
import { Profile } from '../types';

export const mockProfiles: Profile[] = [
  {
    id: 2,
    name: 'Rahul Sharma',
    username: 'rahul_sharma',
    email: 'rahul.sharma@example.com',
    phone: '9876543210',
    password: 'password123',
    age: 32,
    gender: 'Male',
    religion: 'Hindu',
    motherTongue: 'Hindi',
    location: 'Delhi, NCR',
    coordinates: { latitude: 28.7041, longitude: 77.1025 },
    occupation: 'Marketing Manager',
    education: 'MBA',
    height: "6' 0\"",
    about: "A driven marketing professional who believes in living life to the fullest. I value family, honesty, and open communication. Weekends are for long drives, watching cricket, and trying out new cuisines. Searching for a compatible partner who is caring and understanding.",
    interests: ['Cricket', 'Long Drives', 'Foodie', 'Movies'],
    imageUrls: [
      'https://picsum.photos/seed/rahul/400/600',
      'https://picsum.photos/seed/rahul2/400/600',
      'https://picsum.photos/seed/rahul3/400/600'
    ],
    lifestyle: 'Non-Vegetarian',
    isVerified: true,
    privacySettings: {
        showAge: true,
        showLocation: true,
        showOccupation: true,
        showFollowers: true,
        showReligion: true,
        showMotherTongue: true,
        showEducation: true,
        showHeight: true,
        showLifestyle: true,
        showSocialMedia: true,
    },
    socialMedia: [
        { platform: 'Twitter', url: 'https://twitter.com/rahulsharma' },
        { platform: 'Facebook', url: 'https://facebook.com/rahulsharma' }
    ],
    visitorCount: 152,
    joinedDate: '2023-10-15',
    shortlistedByCount: 12,
    blockedByCount: 0,
    lastSeen: new Date(Date.now() - 1000 * 60 * 5).toISOString(), // 5 minutes ago
  },
  {
    id: 3,
    name: 'Aisha Khan',
    username: 'aisha_k',
    email: 'aisha.khan@example.com',
    phone: '9123456780',
    password: 'password123',
    age: 29,
    gender: 'Female',
    religion: 'Muslim',
    motherTongue: 'Urdu',
    location: 'Hyderabad, Telangana',
    coordinates: { latitude: 17.3850, longitude: 78.4867 },
    occupation: 'Doctor',
    education: 'MBBS',
    height: "5' 6\"",
    about: "A compassionate doctor dedicated to my profession. I find joy in helping others and spending quality time with my family. I am an avid reader and love classical music. Looking for an educated and well-settled professional who is family-oriented and has a modern outlook on life.",
    interests: ['Reading', 'Classical Music', 'Family Time', 'Charity'],
    imageUrls: [
      'https://picsum.photos/seed/aisha/400/600',
      'https://picsum.photos/seed/aisha2/400/600',
      'https://picsum.photos/seed/aisha3/400/600'
    ],
    lifestyle: 'Occasionally Non-Vegetarian',
    isVerified: true,
    privacySettings: {
        showAge: false,
        showLocation: true,
        showOccupation: true,
        showFollowers: true,
        showReligion: true,
        showMotherTongue: true,
        showEducation: true,
        showHeight: true,
        showLifestyle: true,
        showSocialMedia: false,
    },
    socialMedia: [
        { platform: 'LinkedIn', url: 'https://www.linkedin.com/in/aisha-khan' }
    ],
    visitorCount: 210,
    joinedDate: '2023-09-21',
    shortlistedByCount: 25,
    blockedByCount: 1,
    lastSeen: new Date(Date.now() - 1000 * 60 * 2).toISOString(), // 2 minutes ago (Online)
  },
  {
    id: 4,
    name: 'Simran Kaur',
    username: 'simran_designs',
    email: 'simran.kaur@example.com',
    phone: '9988776655',
    password: 'password123',
    age: 27,
    gender: 'Female',
    religion: 'Sikh',
    motherTongue: 'Punjabi',
    location: 'Chandigarh, Punjab',
    coordinates: { latitude: 30.7333, longitude: 76.7794 },
    occupation: 'Graphic Designer',
    education: 'B.Des',
    height: "5' 7\"",
    about: "",
    interests: [],
    imageUrls: ['https://picsum.photos/seed/simran/400/600'],
    lifestyle: 'Vegetarian',
    isVerified: false,
    privacySettings: {
        showAge: true,
        showLocation: false,
        showOccupation: true,
        showFollowers: true,
        showReligion: true,
        showMotherTongue: true,
        showEducation: true,
        showHeight: true,
        showLifestyle: true,
        showSocialMedia: true,
    },
    visitorCount: 98,
    joinedDate: '2023-11-05',
    shortlistedByCount: 8,
    blockedByCount: 0,
    lastSeen: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
  },
  {
    id: 5,
    name: 'Vikram Singh',
    username: 'vikram_clicks',
    email: 'vikram.singh@example.com',
    phone: '9234567891',
    password: 'password123',
    age: 34,
    gender: 'Male',
    religion: 'Sikh',
    motherTongue: 'Punjabi',
    location: 'Bengaluru, Karnataka',
    coordinates: { latitude: 12.9716, longitude: 77.5946 },
    occupation: 'Architect',
    education: 'B.Arch',
    height: "5' 11\"",
    about: "An architect by profession and a photographer by passion. I'm someone who is organized and has a keen eye for detail. I enjoy trekking on weekends and exploring historical places. Seeking a partner who is independent, intelligent, and has a positive approach towards life.",
    interests: ['Photography', 'Trekking', 'History', 'Architecture'],
    imageUrls: [
      'https://picsum.photos/seed/vikram/400/600',
      'https://picsum.photos/seed/vikram2/400/600',
    ],
    lifestyle: 'Vegetarian',
    isVerified: true,
    privacySettings: {
        showAge: true,
        showLocation: true,
        showOccupation: false,
        showFollowers: true,
        showReligion: true,
        showMotherTongue: true,
        showEducation: true,
        showHeight: true,
        showLifestyle: true,
        showSocialMedia: true,
    },
    visitorCount: 188,
    joinedDate: '2023-08-12',
    shortlistedByCount: 18,
    blockedByCount: 0,
    lastSeen: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 minutes ago
  },
  {
    id: 6,
    name: 'John Pinto',
    username: 'chef_john',
    email: 'john.pinto@example.com',
    phone: '9345678902',
    password: 'password123',
    age: 31,
    gender: 'Male',
    religion: 'Christian',
    motherTongue: 'Konkani',
    location: 'Goa',
    coordinates: { latitude: 15.2993, longitude: 74.1240 },
    occupation: 'Chef',
    education: 'Hotel Management',
    height: "5' 9\"",
    about: "A chef who loves to express himself through food. I am easy-going, love the beach, and enjoy playing the guitar. Family values are very important to me. Looking for someone who is fun-loving, down-to-earth, and enjoys good food and music.",
    interests: ['Cooking', 'Music', 'Beach', 'Guitar'],
    imageUrls: ['https://picsum.photos/seed/john/400/600'],
    lifestyle: 'Non-Vegetarian',
    isVerified: false,
    privacySettings: {
        showAge: false,
        showLocation: true,
        showOccupation: false,
        showFollowers: true,
        showReligion: true,
        showMotherTongue: true,
        showEducation: true,
        showHeight: true,
        showLifestyle: true,
        showSocialMedia: true,
    },
    visitorCount: 76,
    joinedDate: '2023-11-20',
    shortlistedByCount: 5,
    blockedByCount: 2,
    lastSeen: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), // 5 hours ago
  },
   {
    id: 7,
    name: 'Anjali Menon',
    username: 'anjali_dancer',
    email: 'anjali.menon@example.com',
    phone: '9456789013',
    password: 'password123',
    age: 30,
    gender: 'Female',
    religion: 'Hindu',
    motherTongue: 'Malayalam',
    location: 'Kochi, Kerala',
    coordinates: { latitude: 9.9312, longitude: 76.2673 },
    occupation: 'Classical Dancer',
    education: 'Masters in Fine Arts',
    height: "5' 4\"",
    about: "A professional Bharatanatyam dancer and teacher. Art and culture are the cornerstones of my life. I am spiritual, value tradition, and believe in simple living. Seeking a partner who respects my passion for dance and shares similar traditional and family values.",
    interests: ['Dance', 'Spirituality', 'Culture', 'Teaching'],
    imageUrls: [
      'https://picsum.photos/seed/anjali/400/600',
      'https://picsum.photos/seed/anjali2/400/600',
      'https://picsum.photos/seed/anjali3/400/600',
      'https://picsum.photos/seed/anjali4/400/600',
    ],
    lifestyle: 'Vegetarian',
    isVerified: true,
    privacySettings: {
        showAge: true,
        showLocation: true,
        showOccupation: true,
        showFollowers: true,
        showReligion: true,
        showMotherTongue: true,
        showEducation: true,
        showHeight: true,
        showLifestyle: true,
        showSocialMedia: true,
    },
    visitorCount: 134,
    joinedDate: '2023-07-30',
    shortlistedByCount: 15,
    blockedByCount: 0,
    lastSeen: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(), // 2 days ago
  },
  {
    id: 8,
    name: 'Rohan Joshi',
    username: 'rohan_codes',
    email: 'rohan.joshi@example.com',
    phone: '9567890124',
    password: 'password123',
    age: 29,
    gender: 'Male',
    religion: 'Hindu',
    motherTongue: 'Marathi',
    location: 'Pune, Maharashtra',
    coordinates: { latitude: 18.5204, longitude: 73.8567 },
    occupation: 'Data Scientist',
    education: 'M.S.',
    height: "5' 10\"",
    about: "I'm a logical and curious person, working as a data scientist in a data firm. I love solving puzzles, playing chess, and following the latest tech trends. I'm looking for an intellectually stimulating conversation partner who is also my best friend for life.",
    interests: ['Chess', 'Puzzles', 'Technology', 'Reading Sci-Fi'],
    imageUrls: ['https://picsum.photos/seed/rohan/400/600'],
    lifestyle: 'Occasionally Non-Vegetarian',
    isVerified: false,
    privacySettings: {
        showAge: true,
        showLocation: true,
        showOccupation: true,
        showFollowers: true,
        showReligion: true,
        showMotherTongue: true,
        showEducation: true,
        showHeight: true,
        showLifestyle: true,
        showSocialMedia: true,
    },
    visitorCount: 112,
    joinedDate: '2023-12-01',
    shortlistedByCount: 9,
    blockedByCount: 0,
    lastSeen: new Date().toISOString(), // Online now
  },
  {
    id: 99,
    name: 'Admin',
    username: 'admin',
    email: 'neelustlove@gmail.com',
    phone: '9826482604',
    password: 'Omii@1234',
    age: 35,
    gender: 'Male',
    religion: 'Hindu',
    motherTongue: 'English',
    location: 'System',
    occupation: 'Administrator',
    education: 'Computer Science',
    height: "6' 0\"",
    about: "System Administrator for FindPartners. Ensuring a safe and smooth experience for all users.",
    interests: ['Cybersecurity', 'User Experience', 'Database Management'],
    imageUrls: ['https://ui-avatars.com/api/?name=Admin&background=2F4F4F&color=fff'],
    lifestyle: 'Vegetarian',
    isVerified: true,
    privacySettings: {
        showAge: true,
        showLocation: true,
        showOccupation: true,
        showFollowers: true,
        showReligion: true,
        showMotherTongue: true,
        showEducation: true,
        showHeight: true,
        showLifestyle: true,
        showSocialMedia: true,
    },
    visitorCount: 0,
    joinedDate: '2023-01-01',
    lastSeen: new Date().toISOString(),
    isProfileComplete: true,
  },
];
